class_name EventBus extends Node

signal _resource_changed
signal _open_close_action_panel
signal _world_gen_finished
signal _time_passed(date_times)
signal _work_hour_finished
signal _work_hour_started
